version: 2
updates:

  # Commented out until dependabot can group updates in 1 PR
  # - package-ecosystem: "npm"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   target-branch: nextjs

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: nextjs
